MAX_PLAYERS = 15
MIN_PLAYERS_TO_START = 2
PFP_COUNT = 15
MAX_NICKNAME_LENGTH = 14
MIN_NICKNAME_LENGTH = 1
ROOM_CODE_LENGTH = 4
MAX_ROUNDS = 10
DEFAULT_ROUNDS = 2
DEFAULT_VOTING_TIME = 30
MIN_VOTING_TIME = 15
MAX_VOTING_TIME = 90
SONG_SELECTION_TIMES = [60, 120, 180, 240, 300]
SONG_LENGTHS = [15, 30, 60, 90]
DEFAULT_SONG_SELECTION_TIME = 60
DEFAULT_SONG_LENGTH = 30
GIF_OPTIONS = ["single", "multiple"]
GIF_SUB_OPTIONS = ["one", "three", "four", "six"]
RESULTS_DISPLAY_TIME = 8000
ROOM_IDLE_TIMEOUT = 30 * 60 * 1000

SEAT_COOKIE_NAME = "auxsync_seat"
SEAT_COOKIE_MAX_AGE = 60 * 60
UNCLAIMED_SEAT_TIMEOUT_MS = 30000

RPS_CHOICES = ["rock", "paper", "scissors"]
RPS_WINS_NEEDED = 2
RPS_CHOICE_TIME = 10000
RPS_REVEAL_TIME = 4000
RPS_MAX_ROUNDS = 15

import os
RECONNECT_GRACE_MS = int(os.getenv("RECONNECT_GRACE_MS", "30000"))
YT_SEARCH_LIMIT = 8
GIPHY_TRENDING_LIMIT = 50
GIPHY_SEARCH_LIMIT = 25
MAX_ROOMS = 500
SEARCH_CACHE_MAX_ENTRIES = 50

PHASES = {
    "LOBBY": "lobby",
    "CHOOSING": "choosing",
    "SEARCHING": "searching",
    "LISTENING": "listening",
    "VOTING": "voting",
    "RESULTS": "results",
    "TIEBREAKER": "tiebreaker",
    "GAME_OVER": "game-over",
}
